# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/venkatamunnangi/Programming/own/concurrent-c/concurrent-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/venkatamunnangi/Programming/own/concurrent-c/concurrent-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/venkatamunnangi/Programming/own/concurrent-c/concurrent-c/CMakeFiles /Users/venkatamunnangi/Programming/own/concurrent-c/concurrent-c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/venkatamunnangi/Programming/own/concurrent-c/concurrent-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 01_threads_basic

# Build rule for target.
01_threads_basic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 01_threads_basic
.PHONY : 01_threads_basic

# fast build rule for target.
01_threads_basic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/01_threads_basic.dir/build.make CMakeFiles/01_threads_basic.dir/build
.PHONY : 01_threads_basic/fast

#=============================================================================
# Target rules for targets named 02_threads_args_retval

# Build rule for target.
02_threads_args_retval: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 02_threads_args_retval
.PHONY : 02_threads_args_retval

# fast build rule for target.
02_threads_args_retval/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/02_threads_args_retval.dir/build.make CMakeFiles/02_threads_args_retval.dir/build
.PHONY : 02_threads_args_retval/fast

examples/01_threads_basic.o: examples/01_threads_basic.c.o
.PHONY : examples/01_threads_basic.o

# target to build an object file
examples/01_threads_basic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/01_threads_basic.dir/build.make CMakeFiles/01_threads_basic.dir/examples/01_threads_basic.c.o
.PHONY : examples/01_threads_basic.c.o

examples/01_threads_basic.i: examples/01_threads_basic.c.i
.PHONY : examples/01_threads_basic.i

# target to preprocess a source file
examples/01_threads_basic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/01_threads_basic.dir/build.make CMakeFiles/01_threads_basic.dir/examples/01_threads_basic.c.i
.PHONY : examples/01_threads_basic.c.i

examples/01_threads_basic.s: examples/01_threads_basic.c.s
.PHONY : examples/01_threads_basic.s

# target to generate assembly for a file
examples/01_threads_basic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/01_threads_basic.dir/build.make CMakeFiles/01_threads_basic.dir/examples/01_threads_basic.c.s
.PHONY : examples/01_threads_basic.c.s

examples/02_threads_args_retval.o: examples/02_threads_args_retval.c.o
.PHONY : examples/02_threads_args_retval.o

# target to build an object file
examples/02_threads_args_retval.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/02_threads_args_retval.dir/build.make CMakeFiles/02_threads_args_retval.dir/examples/02_threads_args_retval.c.o
.PHONY : examples/02_threads_args_retval.c.o

examples/02_threads_args_retval.i: examples/02_threads_args_retval.c.i
.PHONY : examples/02_threads_args_retval.i

# target to preprocess a source file
examples/02_threads_args_retval.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/02_threads_args_retval.dir/build.make CMakeFiles/02_threads_args_retval.dir/examples/02_threads_args_retval.c.i
.PHONY : examples/02_threads_args_retval.c.i

examples/02_threads_args_retval.s: examples/02_threads_args_retval.c.s
.PHONY : examples/02_threads_args_retval.s

# target to generate assembly for a file
examples/02_threads_args_retval.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/02_threads_args_retval.dir/build.make CMakeFiles/02_threads_args_retval.dir/examples/02_threads_args_retval.c.s
.PHONY : examples/02_threads_args_retval.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 01_threads_basic"
	@echo "... 02_threads_args_retval"
	@echo "... examples/01_threads_basic.o"
	@echo "... examples/01_threads_basic.i"
	@echo "... examples/01_threads_basic.s"
	@echo "... examples/02_threads_args_retval.o"
	@echo "... examples/02_threads_args_retval.i"
	@echo "... examples/02_threads_args_retval.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

